### ISSUE TITLE
CKEditor 4: editor-element-conflict

### ISSUE THREAD

**Issue by rkemmere** [iceman-fx/gridblock#10]
Wie folgt nachzuprüfen: 

Ein oder mehr Spalten als Layout wählen und einfaches ckeditor 4 modul hinzufügen. Weiteren Inhaltsblock hinzufügen, ebenfalls ckeditor modul - speichern und wieder öffnen. 

`ckeditor.js?buster=1636142947:21 [CKEDITOR] Error code: editor-element-conflict. {editorName: 'ckeditor7a1343f3d5465'}
21:39:51.486 ckeditor.js?buster=1636142947:21 [CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-element-conflict`

**Comment by iceman-fx** [comment]
Das liegt/lag nicht am Gridblock.
Ich habe jetzt eine Anpassung im CKeditor gemacht, da dies aktuell bei mir auch im MBlock auftrat.
