### ISSUE TITLE
Notice bei neuen Contentsettings

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#14]
sofern man die contensettings erweitert erscheint in allen blocks ne notice.
sobald ich den block einmal editiere und speichere ist das weg.

**ich verstehe warum das so ist** trotzdem kann ich nach einer änderung ja nicht alle slices einmal speichern.

![image](https://user-images.githubusercontent.com/330516/141981092-3be8981c-8d28-4cfd-bbaa-6140278b4eba.png)

**Comment by iceman-fx** [comment]
Das kommt bei Dir im Backend oder im Frontend ?

**Comment by olien** [comment]
Beides

**Comment by iceman-fx** [comment]
Erkläre mir bitte nochmal, wie ich das nachstellen kann.
Was machst Du in welcher Reihenfolge?

**Comment by olien** [comment]
nun. ich brauche nur in der contentsettings.json etwas hinzufügen
![image](https://user-images.githubusercontent.com/330516/141988436-35565609-782b-443f-be1f-a98cb82346dd.png)

und schon habe ich in allen slice die notices

![image](https://user-images.githubusercontent.com/330516/141988481-7f15f061-ebb4-4361-849f-3b4840fdc411.png)

**Comment by iceman-fx** [comment]
Alles klar. Checke ich mal und kläre es mit Daniel.

**Comment by iceman-fx** [comment]
Ich kann es leider nicht nachvollziehen.
Bei mir kommen da keine Notices.

Aber Daniel wird es sich mal anschauen.

**Comment by novinet-dsteffen** [comment]
same here. es kommen keine notice. neueste beta 1.0.7 ausprobiert?

**Comment by novinet-dsteffen** [comment]
laut @olien gefixt ;-)

**Comment by iceman-fx** [comment]
Mit der v1.0.7 der CS gefixt oder anderweitig?

**Comment by novinet-dsteffen** [comment]
richtig
