### ISSUE TITLE
Löschen eines einzelnen Inhaltsblocks ermöglichen

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#16]
Sofern ich in einer Spalte einen Inhaltsblock eingelegt habe kann ich diesen nicht mehr löschen...

**Comment by iceman-fx** [comment]
Doch, sobald Du einen weiteren angelegt hast.
Der letzte Block bleibt aktuell immer stehen, analog mBlock.

**Comment by olien** [comment]
Genau. Wenn ich einen zweiten Block anlege klappt es natürlich. Wenn ich aber einen Black angelegt habe und dann keinen mehr möchte muß ich erst noch einen Angelgen um dann dn ersten zu löschen. Bissken kompliziert (wie bei mBlock). Ich nutze öfter leere Spalten (aus Desigingründen :-))

**Comment by iceman-fx** [comment]
OK verstehe.
Macht es da vielleicht Sinn, per Option das Löschen immer erlauben zu können?

**Comment by olien** [comment]
Fand ich gut

**Comment by iceman-fx** [comment]
So, auch dies ist nun in der aktuellen GIT drin.
