### ISSUE TITLE
Wunsch: Drag and Drop der Spalten ermöglichen

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#17]

**Comment by iceman-fx** [comment]
Du meinst, die Spalten zueinander sortieren zu können ...
... also Spalte 1 auf Pos. der Spalte 3?

Dann wäre es folgendes Ergebnis:
1. Spalte 2
2. Spalte 3
3. Spalte 1

**Comment by olien** [comment]
Ja. genau. Nach dem speichern sollte die "Beschriftung" wieder 1,2,3 sein :-))
(so habe ich es in "meinem Modul" und es wird oft genutzt). Ist aber auch kein "muss" wenn es sehr aufwändig ist.

**Comment by iceman-fx** [comment]
Du hast das Sortieren der Spalten bei dir schon Mal umgesetzt?
Wie hast du das gemacht?

**Comment by olien** [comment]
Puh. das war viel, JS und ist nicht nur auf meinem Mist gewachsen... Guck mal hier: https://github.com/olien/das_modul/blob/master/lib/modul/input.php

**Comment by iceman-fx** [comment]
Hi Olli.
Ich bin das Thema gerade mit Daniel durchgegangen.
Es ist schwierig und aufwändig, alle nachgeladenen Eingabefelder, die Template und die Settings sauber und performant unter einen Hut zu bekommen.

Ich würde dies daher erst einmal ruhen lassen.

**Comment by olien** [comment]
Kein Problem. Auch ohne das Drag and Drop ist es ein super AddOn!!
