### ISSUE TITLE
(Unmöglicher) Wunsch?

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#18]
Wenn ich eine Gridblockmodul hinzugefügt habe, dort eine Spalte editiere und dann auf "Block übernehmen" klicke wäre es superklasse, wenn die aktive Spalte auch aktiv bleibt nach dem reload... Ist aber evtl. nicht machbar - oder?

**Comment by iceman-fx** [comment]
Ich schau mal nach, wo ich diesen Wert der aktiven Spalte zwischenspeichern kann.

**Comment by iceman-fx** [comment]
Ist in der aktuellen Git-Version nun drin.
