### ISSUE TITLE
Ein paar Warnings

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#2]
REDAXO (von Github) Frisch installiert.
Developer +  Theme installiert

Gridblock + Plugins ist alliiert 

=

`Warning: filemtime(): stat failed for /Users/oliennotebook/Sites/redaxo-dev/redaxo/data/addons/gridblock/plugins/synchronizer/contentsettings.json in redaxo/src/addons/gridblock/plugins/synchronizer/lib/class.GridblockSynchronizer.php on line 82
Warning: filemtime(): stat failed for /Users/oliennotebook/Sites/redaxo-dev/redaxo/data/addons/gridblock/plugins/contentsettings/contentsettings.json in redaxo/src/addons/gridblock/plugins/synchronizer/lib/class.GridblockSynchronizer.php on line 82
Warning: copy(/Users/oliennotebook/Sites/redaxo-dev/redaxo/data/addons/gridblock/plugins/contentsettings/contentsettings.json): failed to open stream: No such file or directory in redaxo/src/addons/gridblock/plugins/synchronizer/lib/class.GridblockSynchronizer.php on line 85
Falko Müller`

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/140335158-96e72a65-2be8-434c-8417-99ca3ac67b57.png)

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/140335306-4cd576bd-5eb2-4260-8bba-06b2d7511762.png)

**Comment by iceman-fx** [comment]
Danke.

Über die freut sich Daniel sicher schon 😁

**Comment by iceman-fx** [comment]
Ist bei Dir eigentlich das CSS richtig geladen?
Die beiden Buttons hinter der Templateauswahl werden falsch angezeigt.

**Comment by novinet-dsteffen** [comment]
@olien ich kann deinen fehler leider nicht nachvollziehen. ich prüfe im code, ob die datei existiert und nur dann frage ich mit filemtime das alter der datei ab. und das sowohl in Zeile 82/85 als auch 280/283. gleiche funktionalität. kann mir nur so erklären, dass du im theme-ordner keine dateien von contentsettings siehst.

**Comment by novinet-dsteffen** [comment]
@olien ich habe einen kleinen fix rausgebracht. ich hab den fehler gefunden. so müssten zumindest die warnings wegsein. schau mal bitte ob es so funktioniert.
ebenso gleich: rex von github installiert, developer, theme, dann gridblock mit plugins

**Comment by olien** [comment]
Sieht gut aus bei mir!
