### ISSUE TITLE
Notiz bei "leeren" Modul 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#20]
Hi, ich hab ein  Modul in dem ich im Input und Output nur text geschrieben habe (testweise).
wenn ich das nute bekomme ich eine Notice:v

![image](https://user-images.githubusercontent.com/330516/143014413-70709fb2-b86f-46ca-b683-9202022c6876.png)

Es ist auch egal wenn ich den Output des Moduls später sinnvoll fülle...

**Comment by olien** [comment]
Sobald ich Eingabefelder im Input habe erscheint die Notice nicht mehr. Leere Inputs in Modulen habe ich allerdings öfter...

**Comment by iceman-fx** [comment]
Kannst du mir bitte den Modulcode senden, welcher das Problem verursacht?

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/143038764-3e7b612c-cbad-4cf5-aa2c-ac6eea4a6923.png)

**Comment by olien** [comment]
das ist es. sofern nichts oder etwas text drin steht kommt die notice

**Comment by iceman-fx** [comment]
Achso. Alles klar.

**Comment by iceman-fx** [comment]
Ich konnte es zwar selbst nicht testen/nachvollziehen, habe aber noch etwas geändert.
Mit der aktuellen Git-Version sollte es nun nicht mehr erscheinen.
