### ISSUE TITLE
Export / Import Problem 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#21]
moin, wenn ich meine gridblock einstellungen exportiere und die in einer anderen installtion importieren will kommt die fehlermeldung:

`Das Templatearchiv konnte nicht importiert werden, da mindestens eine Datei (template.php, template.json, definition.json) fehlt.`

**Comment by novinet-dsteffen** [comment]
magst du mir mal die import-datei schicken? ich schaus mir gern an.

**Comment by olien** [comment]
Daniel hat nachgeguckt. Danke. Es liegt daran, dass ich Safari so eingestellt habe, dass es Zips beim Download direkt entzückt. Ich habs dann neu komprimiert. Das mag der Importer nicht :-)

Lösung: "Ziel speichern unter" nutzen und das zip auch als zip speichern.

**Comment by novinet-dsteffen** [comment]
Habe trotzdem ein Workaround geschrieben:
https://github.com/iceman-fx/gridblock/commit/32dbb2efbe4e248a4fb9eac3db768a863f548824
