### ISSUE TITLE
Bei Update werden die Settings gelöscht.

### ISSUE THREAD

**Issue by rkemmere** [iceman-fx/gridblock#22]
Leider werden beim Update die eigenen Templates und Settings überschrieben.
Das sollte doch nicht wirklich so sein? 2 Tage Arbeit futsch!

**Comment by iceman-fx** [comment]
Hast Du Update oder einen ReInstall gemacht?

**Comment by rkemmere** [comment]
Update über den Installer von Beta1 auf Beta6

**Comment by iceman-fx** [comment]
Die Templates sollten noch in der DB drin sein (bitte mal mit dem Adminer prüfen).
In der aktuellen Git-Version ist nun zusätzlich eine update.php mit drin, welche die fehlende DB-Spalte nachreicht.
