### ISSUE TITLE
bootstrap-slider.min.css.map fehlt 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#25]
aktuelle GitHub Version 

`Failed to load resource: the server responded with a status of 404 (Not Found)
https://abc.local/assets/addons/gridblock/plugins/contentsettings/bootstrap-slider.min.css.map`

**Comment by novinet-dsteffen** [comment]
ja wird leider vom bootstrap-slider nicht mitgeliefert. ich schau

**Comment by novinet-dsteffen** [comment]
wie befürchtet. es gibt keine map dafür. habs rausgenommen
