### ISSUE TITLE
Umschließendes div beim input

### ISSUE THREAD

**Issue by novinet-dsteffen** [iceman-fx/gridblock#26]
Bitte in der module_input.php einen umschließenden Container um die .nav-tab und .tab-content mit Klasse .gridblock-block ergänzen, damit man auf den gesamten Block zugreifen kann. Dankeschön

**Comment by iceman-fx** [comment]
Ist in der aktuellen Git-Version drin (aber anderer Name ;-))

**Comment by novinet-dsteffen** [comment]
super, danke!
