### ISSUE TITLE
Contentsettings Update Problem (Aktuelle GitHub Version)

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#28]
![image](https://user-images.githubusercontent.com/330516/144008704-9044252c-acb6-4b6d-86e5-0305984fe9ee.png)

**Comment by novinet-git** [comment]
@olien ist deine contentsettings.json fehlerhaft? Das nämlich sagt der Fehler.

**Comment by olien** [comment]
Evtl.. Was hat sich zur Vorgängerversion geändert? Hab ja nur nen update gemacht.

**Comment by olien** [comment]
War wohl mein Problem
