### ISSUE TITLE
Dark Mode Anpassungen 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#29]
![image](https://user-images.githubusercontent.com/330516/144039138-48c1317c-0841-4068-8250-a8fd0257d904.png)

**Comment by iceman-fx** [comment]
Ich habe es gerade gesehen, dass Daniel die Anpassung in seinem Plugin separat hat.

**Comment by novinet-dsteffen** [comment]
Japs aber das sind Dinge zum Teil vom be_style, mform, mblock

**Comment by iceman-fx** [comment]
Zusätzlich erhalte ich noch diese Notice:
Notice: Undefined index: default in redaxo\src\addons\gridblock\plugins\contentsettings\lib\class.GridblockContentSettings.php on line 366

**Comment by novinet-dsteffen** [comment]
hast du die aktuellste version heruntergeladen? diese zeile ist leer in der Klasse

**Comment by iceman-fx** [comment]
Nicht von heute.
Kann ich nochmal checken.

**Comment by novinet-dsteffen** [comment]
@olien kannst du mal bitte prüfen ob es jetzt bei dir sauber läuft?

**Comment by novinet-dsteffen** [comment]
also neueste version von github laden

**Comment by olien** [comment]
Danke. Sieht besser aus bis auf "Inhaltsblock wählen"...

![image](https://user-images.githubusercontent.com/330516/144378780-19576789-fa9d-47c5-b69a-7f6661ffb41d.png)

**Comment by novinet-dsteffen** [comment]
@iceman-fx schaust du da bitte?

**Comment by iceman-fx** [comment]
Ja, gefunden.
Da sich eine Klasse verdünnisiert.

**Comment by iceman-fx** [comment]
Ist erledigt

**Comment by olien** [comment]
Super. Danke. Wäre es nicht schöner wenn Farbe und Cover Farbe die gleichen wie beim REDAXO "Block hinzufügen" wären? so ist es schon recht grell. Wenn Ihr anderer Meinung seid ändere ich das halt nur lokal...

![image](https://user-images.githubusercontent.com/330516/144562418-e2699feb-6be4-4cd3-ba14-264a882ca097.png)

**Comment by iceman-fx** [comment]
Ist es doch.

![1](https://user-images.githubusercontent.com/4291047/144572466-0722f12b-c0e0-4877-aee9-c1d8e8bc3696.PNG)

**Comment by iceman-fx** [comment]
Kann es sein, dass Du die Hover-Farbe meinst?

**Comment by olien** [comment]
Jepp.Sorry für die Unklarheit

**Comment by iceman-fx** [comment]
OK, wird in der heute noch freigeschalteten Version behoben sein.

**Comment by olien** [comment]
👍
