### ISSUE TITLE
Modullayout 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#3]
![image](https://user-images.githubusercontent.com/330516/140337076-cb57f408-bf67-4fa4-9d50-f2b9f82e07e9.png)

`<div class="form-group">
  <label class="col-sm-2">HTML</label>
  <div class="col-sm-10">
    <textarea cols="1" rows="6" class="form-control" name="REX_INPUT_VALUE[1]">REX_VALUE[1]</textarea>
  </div>
</div>

`

**Comment by iceman-fx** [comment]
Kann es sein, dass du. Ich irgendwas Aktiv hast, was das Design anpasst/ändert?
Das sieht schon sehr verschoben bei dir aus.

**Comment by olien** [comment]
Ne. Das ist der Standardcode, den ich immer genutzt habe. Das Mosul ist aus der Modulsammlung:

![image](https://user-images.githubusercontent.com/330516/140465468-77db5bb7-2f2b-40c6-8979-1b7c32ba0db5.png)

**Comment by olien** [comment]
Ausserhalb von Gridblock sieht das so aus:

![image](https://user-images.githubusercontent.com/330516/140466803-04033f4c-b734-4056-93dd-3d28db9c8ba6.png)

**Comment by iceman-fx** [comment]
Ja, aber wird da irgendwo noch anderer CSS Code geladen?
Hast Du schon Rex5.13 am Start -> Darkmode?

**Comment by olien** [comment]
1. nein
2. Ja

Aber im letzen Bild sieht du ja wie es ohne grudblock aussieht. Find ich aber jetzt nicht so schlimm da man dir Module ja entsprechend bauen kann.

**Comment by iceman-fx** [comment]
Naja, es sollte schon so gehen.
Kannst Du den Darkmode mal irgendwie abschalten und es nochmal mit dem Std.Redaxo-Theme testen?

**Comment by iceman-fx** [comment]
Alternativ nehme ich auch gern eine kurze Fernwartung oder so, um den Ausgabecode/CSS mal checken zu können.

**Comment by iceman-fx** [comment]
Was nutzt Du eigentlich für einen Browser?
Die Buttons hinter der Auswahl Layoutvorlage sollten eigentlich alle so hoch wie das Feld sein.

**Comment by iceman-fx** [comment]
Und ich sehe auch, dass durch den Darkmode bei Dir der Drag´n´Drop Button nicht angezeigt wird.

**Comment by iceman-fx** [comment]
Problem gefunden:
Die Modulsammlung nutzt in den Modulen float:left, welche nicht sauber am Ende wieder aufgehoben werden.
Dadurch zieht es meine Elemente mit rein.

Ich werde dass bei mir fixen, allerdings wäre es schön, wenn die Modulsammlung dahingehend korrigiert wird, da andere auch dieses Problem mit den float´s bekommen können.

**Comment by iceman-fx** [comment]
@olien Bitte nochmal mit der aktuellen GH Version testen.
Dieser Anzeigefehler deiner Module sollte jetzt weg sein.

**Comment by olien** [comment]
jo. sieht gut aus:

![image](https://user-images.githubusercontent.com/330516/140475888-24550a69-b487-491a-998f-62239da2a8af.png)

und so sieht es in redaxo 5.12.1 aus:

![image](https://user-images.githubusercontent.com/330516/140476255-35d54ad5-7ad6-4f0d-943f-ec222be26e57.png)

**Comment by iceman-fx** [comment]
Danke für die Screen.
Beim DM sind aktuell ja einige Sachen nicht korrekt sichtbar.

Kann man den DM irgendwie schon jetzt testen mit REX5.12.1 ?

**Comment by iceman-fx** [comment]
Problem fixed
