### ISSUE TITLE
CSS: Darkmode greift bei, obwohl der Mode auf Automatisch steht. D.h. Hell

### ISSUE THREAD

**Issue by rkemmere** [iceman-fx/gridblock#33]
`body:not(.rex-theme-light) .gridblock .slider-track .slider-track-high, body:not(.rex-theme-light) .gridblock .slider-track .slider-track-low {
    background-color: #1F3D3C !important;
}`

Beim Automatischem Modus (siehe Benutzereinstellungen) werden die genannten Klassen rex-theme-light und rex-theme-dark nicht gesetzt, daher kann man das auch nicht per CSS Abfragen

**Comment by iceman-fx** [comment]
Was ist .slider-track .slider-track-high ?
Das kommt im CSS des Addons (/assets/) nicht vor.

**Comment by iceman-fx** [comment]
Ahh ... das ist aus den Plugins.
Ok, ich weise es Daniel zu.

**Comment by novinet-dsteffen** [comment]
sorry, das ist doch einfach nur bescheuert gelöst in REX. die klasse sollte automatisch gesetzt werden, auch wenn kein modus gewählt ist. dann system abfragen und entsprechend setzen. dann müsste man das nicht doppelt schreiben ... 
egal, update ist bei github ;-)

**Comment by iceman-fx** [comment]
Japp. Sehe ich genauso.
