### ISSUE TITLE
Module in Grids werden nicht als verwendet angezeigt

### ISSUE THREAD

**Issue by abra100pro** [iceman-fx/gridblock#34]
In der Modulübersicht werden Module, die in einem Grid stehen, deswegen nicht als verwendet angezeigt. Ich kann somit das Modul löschen, obwohl es noch in einer Seite vorkommt. 

Im Backenderscheint dann im Grid drin:
Dieses Modul existiert nicht! (ID: 22)

Im Frontend erscheint eine Fehlermeldung:
rex_sql_exception
Unable to fetch row.

**Comment by iceman-fx** [comment]
Ja, das ist bekannt.
Leider ist es nicht lösbar, da von Seiten Redaxo dazu keine Einsprungmöglichkeiten bestehen und auch nicht vorgesehen werden sollen.

Einzig ein zus. Abfrage im Frontend kann ich noch einbauen, damit der Fehler nicht geworfen wird.

**Comment by abra100pro** [comment]
Ja, das wäre super - lieber nichts als eine Fehlermeldung.

**Comment by iceman-fx** [comment]
OK, bei fehlenden Inhaltsmodule wird der Block nun im FE übergangen.
