### ISSUE TITLE
Fehler mit PHP 8. Mit PHP 7.4.21 kein Problem

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#35]
![image](https://user-images.githubusercontent.com/330516/154852242-da3c1730-a25a-45eb-b189-852286ebe5a6.png)

![image](https://user-images.githubusercontent.com/330516/154852268-62b08325-17d4-4f6c-a41c-7107d0457223.png)

Developer & Themas installiert

**Comment by novinet-dsteffen** [comment]
Hallo @olien , bitte tausche das JSON_ERROR_NONE durch eine "0". 
@iceman-fx ich habe das auch bereits im Repo angepasst

**Comment by iceman-fx** [comment]
Hat sich dieses Problem geklärt oder besteht es noch?

**Comment by olien** [comment]
Der Fix hat es gelöst. Danke!
