### ISSUE TITLE
MForm 7 - addImagelistField JS Error

### ISSUE THREAD

**Issue by novinet-dsteffen** [iceman-fx/gridblock#36]
Ich glaub es müsste ne ähnliche Anpassung gemacht werden für wie für addMedialistField

**Comment by iceman-fx** [comment]
Aber das müsste doch dann im mform angepasst werden.
Im gridblock haben wir dafür damals keine spezielle Anpassung machen können.

**Comment by olien** [comment]
Das funktioniert  laut Doku auch nicht mit mblock

**Comment by iceman-fx** [comment]
Ich mache es erstmal zu.
