### ISSUE TITLE
Contentsettings Definition bei Nutzung von Kategorien fehlerhaft

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#37]
Wenn man in den Settings einen divider definiert und zus. Kategorien zur Sortierung der Settings nutzt, dann wird der Divider fehlerhaft/falsch einer Kategorie zugewiesen.

![1](https://user-images.githubusercontent.com/4291047/161263754-62bad6d8-7425-4b46-ba92-45a5194913ea.PNG)

**Comment by novinet-dsteffen** [comment]
gib mir mal bitte deine settings. danke
