### ISSUE TITLE
Contentsettings: ein divider kann nicht mehrfach bei Kategorienutzung genutzt werden

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#39]
Wenn ich Kategorien für die Settings definiere und einen divider-Block anlege, so wird dieser nicht zwischen den jeweiligen Settings angezeigt, sondern als "Sonstige Einstellungen" ausgegeben.

Erst nach Zuweisung einer category zum divider wird dieser einmalig in dieser Kategorie angezeigt.
Möchte ich nun mehrere divider in versch. Kats nutzen, so muss für jede Kat einen neuen divider als Block definieren.

Kann man dies irgendwie anders lösen?

**Comment by novinet-dsteffen** [comment]
du kannst jetzt ein "use_last_category": true in json ergänzen z.b. beim divider und du gibst keine kategorie mehr an. dann funktionierts
