### ISSUE TITLE
Contentsettings: kleiner Designbug

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#41]
Die Eingabefelder der Spalten-Settings haben im Gegensatz zum Rest abgerundete Ecken.

![1](https://user-images.githubusercontent.com/4291047/161272398-172fa6a9-957f-4287-92d9-2ac881155d17.png)

**Comment by novinet-dsteffen** [comment]
Erledigt

**Comment by iceman-fx** [comment]
Die sind bei mir in den Column-Settings immer noch abgerundet.
Im Template passt es ;-)
