### ISSUE TITLE
Contentsettings - Checkbox-Bug

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#45]
ich habe einen Bug bei der Checkbox gefunden.
Wenn eine vorhergehende Checkbox aktiv ist, wird eine andere, neue, noch nicht gesetzte bei mir autom. aktiv.

Ich kann es sogar reproduzieren.
In Settings-Tab1 habe ich eine Checkbox und in Settings-Tab4 eine.
Alle haben unterschiedliche Namen etc,
Setze ich die CB in Tab1 nun auf On und speichere den Block, dann ist die CB in Tab4 auch gesetzt, obwohl diese vorher nie angewählt war.

Ich könnte mir vorstellen, dass in Deiner Routine eine Variable nicht vorher genullt wird, wenn der neue Durchlauf für das nächste Element beginnt.

**Comment by iceman-fx** [comment]
In Zeile 481 müsste vor das break noch ein unset() rein:

```
unset($sChecked);
break;
```

https://github.com/iceman-fx/gridblock/blob/e83e87cfa81359b5fc8108284c5fd58d90eb6b8f/plugins/contentsettings/lib/class.GridblockContentSettings.php#L481

**Comment by novinet-dsteffen** [comment]
Erledigt
