### ISSUE TITLE
Contentsettings: Rangeslider ist nicht korrekt links ausgerichtet

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#48]
![1](https://user-images.githubusercontent.com/4291047/166435135-8ace1807-c128-438a-b22e-11470ccb875a.PNG)

**Comment by iceman-fx** [comment]
Ich denke, dies können wir so belassen, da der Slider selbst (nicht der Anfasser) links ausgerichtet ist.
Sieht zwar etwas komisch aus, aber das wäre ok.

**Comment by novinet-dsteffen** [comment]
Erledigt
