### ISSUE TITLE
2 Fehler nach Update auf 1.0.9

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#50]
(Alles andere ist auch aktuell. PHP 8.0.8)

Warning in der Strukturansicht:

`Warning: Uninitialized string offset 4 in redaxo/src/addons/gridblock/lib/gridblock.php on line 152`

![image](https://user-images.githubusercontent.com/330516/171624423-39e2a801-24bb-4fbb-ac30-0d092dc57316.png)

Wood beim Edit:

![image](https://user-images.githubusercontent.com/330516/171624595-73e4fc05-d6f2-42ea-81c1-3db845da222a.png)

`Error thrown with message "Non-static method rex_article_content_gridblock::getCookie() cannot be called statically"

Stacktrace:
#29 Error in /Users/local/Sites/abc/redaxo/src/addons/gridblock/lib/gridblock_article_content.php:210
#28 rex_article_content_gridblock:getModuleSelector in /Users/local/Sites/abc/redaxo/src/addons/gridblock/fragments/gridblock/column.php:114
#27 require in /Users/local/Sites/abc/redaxo/src/core/lib/fragment.php:121
#26 rex_fragment:{closure} in /Users/local/Sites/abc/redaxo/src/core/lib/util/timer.php:63
#25 rex_timer:measure in /Users/local/Sites/abc/redaxo/src/core/lib/fragment.php:126
#24 rex_fragment:parse in /Users/local/Sites/abc/redaxo/src/addons/gridblock/lib/gridblock.php:136
#23 rex_gridblock:genCol in /Users/local/Sites/abc/redaxo/src/addons/gridblock/lib/gridblock.php:113
#22 rex_gridblock:getModuleInput in rex:///module/2/input:30
#21 require in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php:513
#20 rex_article_content_base:{closure} in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php:515
#19 rex_article_content_base:getStreamOutput in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php:524
#18 rex_article_content_editor:editSlice in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content_editor.php:81
#17 rex_article_content_editor:outputSlice in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php:717
#16 rex_article_content_base:renderSlices in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php:428
#15 rex_article_content_base:getArticle in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/lib/article_content.php:105
#14 rex_article_content:getArticle in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/pages/content.edit.php:35
#13 require in /Users/local/Sites/abc/redaxo/src/core/lib/packages/package.php:280
#12 rex_package:includeFile in /Users/local/Sites/abc/redaxo/src/core/lib/be/controller.php:482
#11 rex_be_controller:{closure} in /Users/local/Sites/abc/redaxo/src/core/lib/util/timer.php:63
#10 rex_timer:measure in /Users/local/Sites/abc/redaxo/src/core/lib/be/controller.php:483
#9 rex_be_controller:includePath in /Users/local/Sites/abc/redaxo/src/core/lib/be/controller.php:432
#8 rex_be_controller:includeCurrentPageSubPath in /Users/local/Sites/abc/redaxo/src/addons/structure/plugins/content/pages/content.php:432
#7 require in /Users/local/Sites/abc/redaxo/src/core/lib/packages/package.php:280
#6 rex_package:includeFile in /Users/local/Sites/abc/redaxo/src/core/lib/be/controller.php:482
#5 rex_be_controller:{closure} in /Users/local/Sites/abc/redaxo/src/core/lib/util/timer.php:63
#4 rex_timer:measure in /Users/local/Sites/abc/redaxo/src/core/lib/be/controller.php:483
#3 rex_be_controller:includePath in /Users/local/Sites/abc/redaxo/src/core/lib/be/controller.php:415
#2 rex_be_controller:includeCurrentPage in /Users/local/Sites/abc/redaxo/src/core/backend.php:238
#1 require in /Users/local/Sites/abc/redaxo/src/core/boot.php:143
#0 require in /Users/local/Sites/abc/redaxo/index.php:9

`

**Comment by iceman-fx** [comment]
Also den ersten Fehler bekomme ich bei mir nicht, habe aber eine kleine Anpassung eingestellt.
Den 2. habe ich gefunden.

Bitte teste es mal mit der aktuellen Git Version.

**Comment by olien** [comment]
Danke. Mit der Version sind beide Fehler weg!

**Comment by olien** [comment]
Danke 👍
