### ISSUE TITLE
Es hagelt Warnings nach dem update von der vorletzten auf die aktuelle Version 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#51]
![image](https://user-images.githubusercontent.com/330516/175527675-bb9fa291-137e-40b1-bae6-d1c98804262d.png)

![image](https://user-images.githubusercontent.com/330516/175527536-d8299359-4bb0-49e9-8679-4fa673d6ab9a.png)

![image](https://user-images.githubusercontent.com/330516/175527562-72b8e2b3-38bc-4df9-b4cb-e65f1f3f0af3.png)

nicht sooo schön :-)

**Comment by novinet-dsteffen** [comment]
siehe update.
