### ISSUE TITLE
Möglichkeit zum Anfügen der Einheit bei einem Slider schaffen

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#52]
Die Slider bei den Contentsettings zeigen derzeit nur den Wert im Tooltip an.
Toll wäre es, wenn man über ein `"text": "px"` Attribut eine Einheit definieren kann, welche dann im Tooltip des Slider (oder dahinter, falls kein Tooltip genutzt wird) mit ausgegeben wird.

"115" wird dann zu "115px"

**Comment by novinet-dsteffen** [comment]
leider habe ich keine möglichkeit gefunden.
genutzt wird ja der slider hier: https://github.com/seiyria/bootstrap-slider und der bietet diese möglichkeit nicht

**Comment by novinet-git** [comment]
In der neuen Version kann man mit "slider-unit" die einheit mitgeben ;-)
wird dann nach dem value angestellt
