### ISSUE TITLE
Wiederverwendbarkeit von Felddefinitionen (Optionen) mit anderem Key möglich?

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#53]
Wäre es irgendwie möglich, die definierten Felder auf einfache Art nochmal zu verwenden und nur lediglich den Key dabei ändern zu müssen?

Bsp: 
Border oder ShapeDivider haben praktisch immer die gleichen Einstellungen je Position (oben+unten), z.B. Auswahl Bild, Farbe, Höhe, Breite, etc.
Aktuell muss man je Position (oder Ausgabegröße) jedes Feld mehrfach anlegen, obwohl die sich nur im Key unterscheiden.

```
{
	"category": "design",
	"key": "shadivTopImage",
	"label": "... oder Bild",
	"type": "media",
	"preview": "1",
	"types": "jpg,jpeg,gif,png,svg"
},

{
	"category": "design",
	"key": "shadivBottomImage",
	"label": "... oder Bild",
	"type": "media",
	"preview": "1",
	"types": "jpg,jpeg,gif,png,svg"
},

{
	"category": "design",
	"key": "bgImage",
	"label": "... oder Bild",
	"type": "media",
	"preview": "1",
	"types": "jpg,jpeg,gif,png,svg"
},
```

**Comment by novinet-dsteffen** [comment]
siehe neueste version. du kannst einfach "parent" ergänzen. du benötigst also "nur" noch "key" und "parent", der rest wird dann überschrieben, außer das element hat eigene optionen gesetzt

beispiel:
`		{
			"category": "layout",
			"key": "marginTop",
			"label": "Außenabstand Oben",
			"type": "select",
			"data": {
				"mt-0": "Kein",
				"mt-1": "Sehr klein",
				"mt-2": "Klein",
				"mt-3": "Mittel",
				"mt-4": "Groß",
				"mt-5": "Sehr groß"
			},
			"default": "mt-0"
		},
		{
			"key": "marginTest",
			"label": "margin Test",
			"parent": "marginTop",
			"default": "mt-2"
		},`

**Comment by iceman-fx** [comment]
Ich wollte dies gerade einbauen, scheint aber leider nicht zu klappen.

Wenn ich dies so einbaue, wie beschrieben, dann ändert sich nichts.
Außer ... dass nun der gepsicherte Wert beim ersten Element nicht mehr gezogen und selektiert wird.
