### ISSUE TITLE
.map Dateien fehlen 

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#54]
![image](https://user-images.githubusercontent.com/330516/175546539-eaca88a9-9865-4760-ad19-cb5829c5dbc6.png)
![image](https://user-images.githubusercontent.com/330516/175546728-317d9cd9-e806-4cb3-aa62-9cdea87ff1ef.png)

**Comment by novinet-dsteffen** [comment]
hab ich nun ergänzt
