### ISSUE TITLE
PHP 8.1 | preg_replace(): Passing null to parameter #2 ($replacement) of type array|string is deprecated

### ISSUE THREAD

**Issue by dennisosaj** [iceman-fx/gridblock#55]
The solution would be as following in `redaxo/src/addons/gridblock/lib/gridblock_var_replacer.php` from line 106 and below:
<img width="1903" alt="Screenshot 2022-06-28 at 09 28 11" src="https://user-images.githubusercontent.com/48364940/176119520-a010ab00-daa4-4390-80b6-79bb7f7dbe84.png">

**Comment by iceman-fx** [comment]
Bitte mal die aktuelle GIT-Version testen.
Damit sollte die Meldung weg sein.
