### ISSUE TITLE
Idee: vordefinierte Zusammenstellungen

### ISSUE THREAD

**Issue by novinet-git** [iceman-fx/gridblock#56]
Ich würde gerne noch einen Schritt weiter gehen. Könnte man ganze Blöcke als Vorlagen abspeichern?
Angenommen ich hab nen 2-Spalter

links die Module
- Überschrift
- Text
- Button

rechts dann das Modul
- Bild

Dazu habe ich die Contentsettings auch entsprechend gesetzt, z.B. mit Hintergrundfarbe, Abstände, etc.
Wie cool wäre es denn, wenn ich dann das ganze abspeichern könnte als Vorlage. Wenn man dann ein neues Gridblockelement hinzufügt, könnte man entweder aus den Templates wählen oder aber aus vorhandenen "Zusammenstellungen". 
Könnte man über Tabs lösen ...

**Comment by iceman-fx** [comment]
Was stellst Du Dir unter eine "Tab-Lösung" vor?
Aus meiner Sicht wäre es besser direkt in der Templateauswahl untergebracht.

**Comment by novinet-git** [comment]
![Bildschirmfoto 2022-06-28 um 10 46 38](https://user-images.githubusercontent.com/46102276/176136568-28abb7da-6d7a-4b42-98d6-817a1c1a2c0a.png)

**Comment by novinet-git** [comment]
ich würde es nicht mischen sondern klar trennen

**Comment by iceman-fx** [comment]
Eine klare Trennung würde man auch mit einer Liste hinbekommen.

**Comment by iceman-fx** [comment]
Über die Speicherung bin ich mir etwas unschlüssig.

**Comment by novinet-git** [comment]
können wir schließen. ich hab das im addon nv_modulepreview als neues feature umgesetzt
