### ISSUE TITLE
User-Contensettings.json möglich?

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#57]
Wäre es denkbar, dass man zusätzliche (globale) contentsettings.json anlegen und einlesen lassen kann?

Vorteil:
Man könnte eine default-JSON anlegen, welche alle gewünschten Settings beinhaltet.
Über eine zus. User-JSON würde man dann nur die Projektweiten Änderungen überschreiben, ohne die Originaldatei anfassen zu müssen.
Damit könnte man einfacher Updates der default-JSON einbringen, ohne jedes mal jede Projekt-JSON bearbeiten zu müssen.

**Comment by novinet-dsteffen** [comment]
lustig, hatte sowas bei den modulesettings und habs dann extra für die GBCS rausgenommen. wie stellst du dir das vor? wo würde die liegen? im project ordner? oder möchtest du das in der gb config definieren können?

**Comment by novinet-dsteffen** [comment]
Ist in der neuen Version eingefügt.
8e17be322984b9b114a8834ac6a92a0be92d5720
