### ISSUE TITLE
Contentsettings: neuer default entfernt Select-Auswahl

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#58]
Wenn ich bei einem Settingsfeld den default nachträglich ändere, dann wird im BE beim Feld nicht mehr der gespeicherte Wert angezeigt, wenn man diesen Block editiert.

Bsp:
- alter default war ""
- im Block wurde ausgewählt und gespeichert: "pdH-md"
- jetzt den default in der settings auf "pdH-md" geändert
- den Block zum editieren öffnen -> Auswahl des Feldes steht auf "kein Abstand" (ausgegraut)

Stellt man den alten Zustand ("") wieder her, wird es auch im BE wieder korrekt angezeigt.

Vorher:
![vorher](https://user-images.githubusercontent.com/4291047/178201446-59639fdd-4921-459b-86fe-5997d972a292.PNG)

Nachher:
![nachher](https://user-images.githubusercontent.com/4291047/178201462-17f6426c-9857-47d3-89c8-43ea0e7c5aab.PNG)

**Comment by novinet-dsteffen** [comment]
hmmm ... getestet und kanns nicht nachvollziehen. bei mir funktioniert es korrekt

**Comment by georgkaser** [comment]
Also ich hab auch Probleme mit Content Settings und den Selects: Wenn das Contentsetting Plugin installiert ist, dann übernimmt es Änderungen beim Select nicht - deaktiviert man es, funktioniert es korrekt:

Modul mit aktiviertem Contentsetting-Plugin:
https://user-images.githubusercontent.com/6472869/226631554-f191eef4-f487-4bf5-981f-275f29b59904.mp4

Modul mit deaktiviertem Contentsetting-Plugin:
https://user-images.githubusercontent.com/6472869/226631748-5a55c8dd-e451-437f-81a6-0cff9d701596.mp4

**Comment by georgkaser** [comment]
Ja, bei mir geht es jetzt auch. Danke für die schnelle Reparatur! Supercooles Addon übrigens :)
