### ISSUE TITLE
Template-Import: Prio wird ab 10. Template falsch gesetzt

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#59]
![1](https://user-images.githubusercontent.com/4291047/178254081-f0d00cc0-da50-446d-ab69-ebe86def71c7.PNG)

**Comment by novinet-dsteffen** [comment]
kannst du mir mal bitte deine import-datei zum testen geben?

**Comment by iceman-fx** [comment]
Kann es sein, dass die Prio einfach beim Import aus dem Template 1:1 übernommen wird?
Die 18 + 19 steht nämlich im Template, welches importiert wurde.

Die Prio wird sicher von Dir nicht neu gesetzt beim Import.
