### ISSUE TITLE
Frage / Wunsch: Gibt es eine Möglichkeit zu prüfen ob Module innerhalb Gridblock genutzt werden?

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#6]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/330516/140510245-c89ce413-8193-4f3e-9e1c-3631346e8b93.png">

**Comment by iceman-fx** [comment]
Meinst Du jetzt praktisch den Rückweg, ob bereits in Artikeln Gridblöcke mit Inhalten angelegt wurden?

An welcher Stelle sollte dies getestet werden?

**Comment by olien** [comment]
Ja. Ansonsten könnte ja jemand in der Modulübersicht "ausersehen" Module löschen....

**Comment by iceman-fx** [comment]
Ich schau Mal, ob man dies irgendwie hinbekommt, ohne am Core rumschrauben zu müssen.

**Comment by iceman-fx** [comment]
Ich wüsste aktuelle nicht, wie man dies hinbekommen kann, ohne das Ausgabefragment der Module-Seite ändern zu müssen.
Leider gibt es keine EPs für die Ausgabe in diesem Bereich und mit dem OP-Filter habe ich es bisher nicht hinbekommen.

**Comment by olien** [comment]
ok. kein Problem. war auch nur so eine Idee....

**Comment by iceman-fx** [comment]
Das ist ja eine berechtigte und sinnvolle Idee.
Ich weiß halt nur nicht, wie ich dort problemlos und sicher an die Statusanzeige gelangen soll, da es leider keine EPs an dieser Stelle gibt.
