### ISSUE TITLE
CS: slider auf volle Breite bringen

### ISSUE THREAD

**Issue by iceman-fx** [iceman-fx/gridblock#60]
Macht es Sinn, den CS-Slider auf die volle Breite wie die Sleect und Inputfelder zu bringen?
Vorteil: Die Step-Abstände wären i.d.R. größer/besser wählbar, wenn ziemlich kleine Steps notwendig sind.

Dazu wären folgende CSS-Anpassungen notwendig:
```
.slider.slider-horizontal {
    width: auto;
    min-width: 210px;
}
.slider {
    display: block;
}
```

**Comment by novinet-dsteffen** [comment]
Mit dem neuesten Commit erledigt
