### ISSUE TITLE
Probleme mit mblock 3.4.5

### ISSUE THREAD

**Issue by novinet-dsteffen** [iceman-fx/gridblock#61]
Nach dem Update auf den neuesten mblock 3.4.5 bleiben alle felder leer, wenn man ein modul "übernimmt" - also im nachhinein bearbeitet. lädt man die seite dann einfach neu, sind die änderungen wieder drin.

**Comment by iceman-fx** [comment]
Gibt es Fehlerausgaben in der Konsole?

**Comment by iceman-fx** [comment]
Bin mir aktuell nicht sicher, ob man dies umgehen/abfangen kann:
https://github.com/FriendsOfREDAXO/mblock/commit/f409ce63ca296606f3cd9b951347e2448a2b5142

**Comment by iceman-fx** [comment]
Problem liegt eindeutig am MBlock/MForm, aufgrund der Abfrage der Feldwerte direkt aus dem $_POST.
Dieses ist nicht gefüllt, da Gridblock wie eine Art Box um den MB/MF gelegt wird und die Werte sich damit nicht mehr direkt im S_POST befinden.

Lösung nur die Anpassung von MB/MF möglich.

**Comment by iceman-fx** [comment]
Ich mach dies hier mal zu, da es im MBlock gelöst werden muss.
