### ISSUE TITLE
mForm Multiselects Funtkionieren nicht  (Alle AddOns aktuell)

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#62]

**Comment by olien** [comment]
https://user-images.githubusercontent.com/330516/201921556-22b3c2c1-9c8d-4557-ab6a-39f6bfffb36f.mov

**Comment by iceman-fx** [comment]
Was meinst du mit "alle addons aktuell"?

Hattest du das nicht vor kurzer Zeit schon mal, wo es aber bei mir funktionierte?

**Comment by olien** [comment]
Kann sein. Alle AddOns sind auf dem aktuellen Stand). 

Vielleicht können wir morgen mal n screensharing machen und gucken wo wir Unterschiede haben?

**Comment by iceman-fx** [comment]
Diese Woche wird das nix.
Müssen wir nächste Woche Mal schauen.

**Comment by iceman-fx** [comment]
Ich mach hier Mal zu, da es ein MForm Problem ist.
