### ISSUE TITLE
PHP 8.2.0 Deprecated Meldungen

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#63]
![image](https://user-images.githubusercontent.com/330516/225620477-c9862371-5974-4ca9-854b-572ec9ed1006.png)

**Comment by olien** [comment]
Ich habe etwas Angst vor den Breaking Changes ;-)

**Comment by iceman-fx** [comment]
@olien Sind die Meldungen bei Dir jetzt weg?

**Comment by olien** [comment]
Nein. Gab es ein Update???

**Comment by iceman-fx** [comment]
Ja, Daniel hat ein Update gemacht.
Aber ich kann Dir nicht sagen, ob es da schon mit eingeflossen ist.

**Comment by olien** [comment]
Kam nix im Installer ...

**Comment by iceman-fx** [comment]
Nicht im Installer ... Hier bei GitHub

**Comment by novinet-dsteffen** [comment]
Ich hab dazu nix gemacht :-)

**Comment by olien** [comment]
Sorry für die später Rücktedung. Soll ich das hier die aktuelle Version testen? (mein Log läuft voll :-))

![image](https://github.com/iceman-fx/gridblock/assets/330516/934339d3-faf5-474b-909d-25b6b966762a)

**Comment by olien** [comment]
Gibt es hier schon etwas neues?

**Comment by iceman-fx** [comment]
@novinet-dsteffen

**Comment by novinet-dsteffen** [comment]
Sorry, völlig untergegangen. Schaue ich mir die Woche an.

**Comment by olien** [comment]
Danke sehr… (läuft ja trotzdem alles ;-))

**Comment by novinet-dsteffen** [comment]
Hallo zusammen, Update ist von Oli getestet, läuft problemlos. @iceman-fx bitte neue Version releasen.
