### ISSUE TITLE
Prio wird nicht richtig gesetzt

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#64]
REDAXO + AddOns aktuell.
PHP 8.2.

Contentsettings und synchronizer aktiv

**Comment by iceman-fx** [comment]
Meinst Du die Prio bei den GB-Templates zur Sortierung der Templateliste?

Stimmt denn die Sortierung, wenn Contentsettings und synchronizer nicht aktiv sind und Du einen Eintrag neu speicherst?

**Comment by iceman-fx** [comment]
Problem gefunden und behoben.
