### ISSUE TITLE
Cookie im Frontend - notwendig?

### ISSUE THREAD

**Issue by olien** [iceman-fx/gridblock#66]
https://web-check.xyz/results/https%3A%2F%2Fkreischer.de

![image](https://github.com/iceman-fx/gridblock/assets/330516/138d3531-51a0-4673-b333-c860261bdde7)

**Comment by iceman-fx** [comment]
Kommt dies auch bei einem frischen Aufruf des Frontends oder nur/erst wenn Du vorher im BE warst?

**Comment by olien** [comment]
Sorry für die späte Antwort (irgendwie bekomme ich keine Mails von GitHub). Die Cookies sind tatsächlich nur da wenn es ne backend Session gibt. Kann also zu hier. Danke!
