### ISSUE TITLE
JavaScript Problem mit MForm LinkListField

### ISSUE THREAD

**Issue by georgkaser** [iceman-fx/gridblock#67]
Das LinkListField von MForm lässt sich in Gridblock nicht sortieren. Ohne Gridblock funktioniert das Modul.

Folgende Fehlermeldung:

![image](https://github.com/iceman-fx/gridblock/assets/6472869/2e762a9c-e58d-46ec-9a88-1a8c5c1fbeb0)

**Comment by iceman-fx** [comment]
Scheint mir eher ein Problem des MBlock selbst zu sein.
Bestimmt liegt es wieder an den übergebenen IDs, wo im MBlock nur Zahlen zulässig sind.

**Comment by georgkaser** [comment]
Hmm... und was heißt das jetzt? Kann man MForm in Gridblock nicht verwenden? Ich hab das Linkfeld wie in der MForm Dokumentation angelegt: `->addLinklistField(1,array('label'=>'Artikel'))`. Das Modul funktioniert ohne Gridblock wunderbar?

Wäre schade, weil das Gridblock Addon REDAXO unheimlich flexibel macht. Aber es treten immer wieder Fehler auf (z.B. der Caching Bug den ich schon mal gepostet habe tritt immer wieder sporadisch auf) - so kann ich das dem Kunden nicht geben.

**Comment by iceman-fx** [comment]
Mit MForm-Einbindungen gab es schon öfters Probleme, da meist die JS-Übergabewerte nicht als String erfolgen.
Da kann nur das Team vom MForm nachschauen und ggf. eine Anpassung vornehmen.

Wir nutzen das Gridblock praktisch in allen Kundenpräsenzen, verzichten aber (auch ohne Gridblock) prinzipiell auf MForm.
MBlock allerdings nutzen sehr oft, dort dann in der HTML-Schreibweise.

Was das Caching angeht, so habe ich da noch nirgends Probleme gehabt - selbst auf verschiedenen Servern.
Aber dies betrifft ja bei Dir anscheinend nur das contentsettings-Plugin.

**Comment by georgkaser** [comment]
Nein, ich hatte das Contentsettings-Plugin sogar extra ausgebaut. Dann war das Problem kurz weg und dann wieder da. Ich denke es liegt am cke5. Aber egal, ich kann den Fehler einfach nicht reproduzieren. Manchmal tritt er auf, manchmal nicht - voll nervig. Hab den cke5 jetzt gegen ckeditor ersetzt - bisher ist der Fehler nicht mehr aufgetreten.

Zurück zu MForm: Ich verwende überall MForm. Schade dass es damit Probleme gibt. Muss ich überlegen ob ich lieber auf MForm oder auf Gridblock verzichte. Danke.
