### ISSUE TITLE
Modul mit Ckeditor wirft bei mehrspaltig Fehler

### ISSUE THREAD

**Issue by rkemmere** [iceman-fx/gridblock#8]
Leider das bekannte Problem, wenn man ein Modul mit Ckeditor hat und dieses in 2 oder mehr Spalten verwenden will.

`ckeditor.js?buster=1565943360:359 Uncaught The editor instance "ckeditor8263e4c712873" is already attached to the provided element.`

**Comment by iceman-fx** [comment]
Der Editor funktioniert aber trotzdem korrekt.

**Comment by iceman-fx** [comment]
Ich wüsste jetzt nicht, wie man das umgehen kann bzw. dem Editor beibringen kann.
Hast Du eine Idee.

**Comment by rkemmere** [comment]
> Der Editor funktioniert aber trotzdem korrekt.

Mehrspaltig geht das nicht mehr! Nur eine Instanz klappt.

**Comment by rkemmere** [comment]
Das Problem gab es bei mform / mblock auch schonmal. Es muss ein rex:ready getriggert werden, da dieser dann vom ckeditor beachtet wird.

**Comment by iceman-fx** [comment]
Bei mir klappt das Mehrspaltung oder mehrere cke innerhalb einer Spalte.
Welchen ck nutzt du denn?

Ich den cke4.

**Comment by iceman-fx** [comment]
Das Rex:ready wird eigentlich getriggert.

**Comment by rkemmere** [comment]
Vergesst es! Ich habe den Ckeditor nochmal gelöscht und nochmal neu in Version 4.16.1 runtergeladen und installiert, damit gehts nun!
