### ISSUE TITLE
Bei nicht geänderten default Wert im Block erfolgt notice

### ISSUE THREAD

**Issue by rkemmere** [iceman-fx/gridblock#9]
Wenn in der contentsettings ein key mit default definiert ist und dann im Modul keine Änderung an dem Key vorgenommen wird, also der Default gelassen wird, erzeugt das folgende Fehlermeldung:

`Notice: Undefined property: stdClass::$column_alignment`

`{
      "key": "column_alignment",
      "label": "Ausrichtung Inhalt",
      "type": "select",
      "data": {
        "align-self-xs-top": "Oben",
        "align-self-xs-center": "Mitte",
        "align-self-xs-end": "Unten"
      },
      "default": "align-self-xs-top"
    },	`

**Comment by novinet-dsteffen** [comment]
schau ich mir an!

**Comment by novinet-dsteffen** [comment]
@rkemmere schau mal hier:
https://github.com/iceman-fx/gridblock/commit/562d57094e9ac6191e5e896e58582655c64cd892
Bei mir sind die notice jetzt weg

**Comment by rkemmere** [comment]
Sieht gut aus! Tritt Aktuell nicht mehr auf.
